---
all:
  children:

    # The machine where CheckMK server will be installed
    checkmk_server:
      hosts:
        a01apvl00763.adeo.no:
          ansible_become: true

    # Linux servers to be monitored with the CheckMK agent
    linux_hosts:
      hosts:
        linux01.example.com:
          ansible_user: ansible
          ansible_become: true
        linux02.example.com:
          ansible_user: ansible
          ansible_become: true

    # Windows servers to be monitored with the CheckMK Windows agent
    windows_hosts:
      hosts:
        windows01.example.com:
          ansible_user: ansible
          ansible_password: "{{ vault_windows_ansible_password }}"
          ansible_connection: winrm
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore
        windows02.example.com:
          ansible_user: ansible
          ansible_password: "{{ vault_windows_ansible_password }}"
          ansible_connection: winrm
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore

    # Network devices monitored via SNMP (no agent installed)
    network_devices:
      hosts:
        switch01.example.com:
          checkmk_snmp_version: "2c"
        router01.example.com:
          checkmk_snmp_version: "2c"
